previewsEnabled: true
previewsExpireAfterDays: 1
databases:
  - name: convo-db-test123
    databaseName: convo
    user: convo
    postgresMajorVersion: 14
    plan: starter
    previewPlan: starter

services:
  - type: web
    name: convo-web-test123
    plan: starter
    env: ruby
    repo: https://github.com/render-examples/rails-6
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: convo-db-test123
          property: connectionString
    domains:
      - notarealdomaintesttest.com
    previewPlan: starter
    initialDeployHook: bundle exec rake db:seed
  - type: worker
    name: convo-queue-test123
    env: ruby
    repo: https://github.com/render-examples/sidekiq
    buildCommand: "bundle install"
    startCommand: "bundle exec sidekiq -r ./main.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: convo-db-test123
          property: connectionString
    previewPlan: starter
